### ISSUE TITLE
Javascript Date to MYSQL Date

### ISSUE THREAD

**Issue by Zeromiya** [DOSexample/TS2#2]
The query on character creation gives error as it is wrong because of the time format differences of Javascript and MYSQL you can replace `'now()'` statement with a 
```new Date().toISOString().slice(0, 19).replace('T', ' ');```
statement or use any Date modules to get it right way such as moment.js

**Comment by DOSexample** [comment]
add function get datetime in s_game
var ReturnTime = function () 
{
	var date = new Date();
	return sprintf( '%04d-%02d-%02d %02d:%02d:%02d', date.getFullYear(), ( date.getMonth() + 1 ), date.getDate(), date.getHours(), date.getMinutes(), date.getSeconds() );
}

**Comment by Zeromiya** [comment]
On the other hand it occurred to me why we are not using Timestamp field and avoid the function ? In this manner we can use `now()` function or CURRENT_TIMESTAMP.
We can arrange the auto update of CURRENT_TIMESTAMP for the field to not update on update queries. (If we don't want a field which is updated every time character changes it's name)
